#!/usr/bin/env fish
# shellcheck shell=fish
# - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  GEN_SCRIPT_REPLACE_VERSION
# @@Author           :  GEN_SCRIPT_REPLACE_AUTHOR
# @@Contact          :  GEN_SCRIPT_REPLACE_EMAIL
# @@License          :  GEN_SCRIPT_REPLACE_LICENSE
# @@ReadME           :  GEN_SCRIPT_REPLACE_FILENAME --help
# @@Copyright        :  GEN_SCRIPT_REPLACE_COPYRIGHT
# @@Created          :  GEN_SCRIPT_REPLACE_DATE
# @@File             :  GEN_SCRIPT_REPLACE_FILENAME
# @@Description      :  GEN_SCRIPT_REPLACE_DESC
# @@Changelog        :  GEN_SCRIPT_REPLACE_CHANGELOG
# @@TODO             :  GEN_SCRIPT_REPLACE_TODO
# @@Other            :  GEN_SCRIPT_REPLACE_OTHER
# @@Resource         :  GEN_SCRIPT_REPLACE_RES
# @@Terminal App     :  GEN_SCRIPT_REPLACE_TERMINAL
# @@sudo/root        :  GEN_SCRIPT_REPLACE_SUDO
# @@Template         :  shell/fish
# - - - - - - - - - - - - - - - - - - - - - - - - -
trap '' EXIT
# - - - - - - - - - - - - - - - - - - - - - - - - -
# script variables
set -g APPNAME (path basename (status filename))
set -g VERSION GEN_SCRIPT_REPLACE_VERSION
set -g RUN_USER $USER
set -g SET_UID (id -u)
set -g SCRIPT_SRC_DIR (path dirname (status filename))
set -g GEN_SCRIPT_REPLACE_ENV_CWD $PWD
# - - - - - - - - - - - - - - - - - - - - - - - - -
# "output" "number"
if set -q NO_COLOR; or test "$SHOW_RAW" = true
  # Disable colorization
  function __printf_color -d 'print output'
    printf '%s\n' $argv[1]
  end
else
  function __printf_color -d 'print output'
    set -l color $PRINTF_SET_RESET
    test (count $argv) -ge 2; and set color $argv[2]
    if isatty 1
      printf '%b%s%b\n' $color $argv[1] $PRINTF_SET_RESET
    else
      printf '%s\n' $argv[1]
    end
  end
end
# - - - - - - - - - - - - - - - - - - - - - - - - -
# check for command
function __cmd_exists -d "Check if application exists in the path"
  command -q $argv[1]
end
function __function_exists -d "Check if command is a function"
  functions -q $argv[1]
end
# - - - - - - - - - - - - - - - - - - - - - - - - -
# custom functions

# - - - - - - - - - - - - - - - - - - - - - - - - -
# Define Variables
set -g PRINTF_SET_BLACK '\e[1;30m'
set -g PRINTF_SET_RED '\e[0;31m'
set -g PRINTF_SET_GREEN '\e[0;32m'
set -g PRINTF_SET_YELLOW '\e[1;33m'
set -g PRINTF_SET_BLUE '\e[1;34m'
set -g PRINTF_SET_PURPLE '\e[0;35m'
set -g PRINTF_SET_CYAN '\e[0;36m'
set -g PRINTF_SET_WHITE '\e[1;37m'
set -g PRINTF_SET_RESET '\e[0m'
set -g GEN_SCRIPT_REPLACE_ENV_EXIT_STATUS 0
# - - - - - - - - - - - - - - - - - - - - - - - - -
# Main application
__printf_color "User ID: $SET_UID"
__printf_color "User Name: $RUN_USER" $PRINTF_SET_YELLOW
__printf_color "Script Name: $APPNAME" $PRINTF_SET_BLUE
__printf_color "Version: $VERSION" $PRINTF_SET_PURPLE
__printf_color "Current Working directory: $GEN_SCRIPT_REPLACE_ENV_CWD" $PRINTF_SET_CYAN
# - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
# - - - - - - - - - - - - - - - - - - - - - - - - -
exit $GEN_SCRIPT_REPLACE_ENV_EXIT_STATUS
# - - - - - - - - - - - - - - - - - - - - - - - - -
# ex: ts=2 sw=2 et filetype=fish
