#!/usr/bin/env zsh
# - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  GEN_SCRIPT_REPLACE_VERSION
# @@Author           :  GEN_SCRIPT_REPLACE_AUTHOR
# @@Contact          :  GEN_SCRIPT_REPLACE_EMAIL
# @@License          :  GEN_SCRIPT_REPLACE_LICENSE
# @@ReadME           :  GEN_SCRIPT_REPLACE_FILENAME --help
# @@Copyright        :  GEN_SCRIPT_REPLACE_COPYRIGHT
# @@Created          :  GEN_SCRIPT_REPLACE_DATE
# @@File             :  GEN_SCRIPT_REPLACE_FILENAME
# @@Description      :  GEN_SCRIPT_REPLACE_DESC
# @@Changelog        :  GEN_SCRIPT_REPLACE_CHANGELOG
# @@TODO             :  GEN_SCRIPT_REPLACE_TODO
# @@Other            :  GEN_SCRIPT_REPLACE_OTHER
# @@Resource         :  GEN_SCRIPT_REPLACE_RES
# @@Terminal App     :  GEN_SCRIPT_REPLACE_TERMINAL
# @@sudo/root        :  GEN_SCRIPT_REPLACE_SUDO
# @@Template         :  shell/zsh
# - - - - - - - - - - - - - - - - - - - - - - - - -
# shellcheck disable=all
# - - - - - - - - - - - - - - - - - - - - - - - - -
# script variables
APPNAME="${0:t}"
VERSION="GEN_SCRIPT_REPLACE_VERSION"
RUN_USER="${USER}"
SET_UID="${UID}"
SCRIPT_SRC_DIR="${0:A:h}"
GEN_SCRIPT_REPLACE_ENV_CWD="${PWD}"
# - - - - - - - - - - - - - - - - - - - - - - - - -
# script functions
if [[ -n "${NO_COLOR+x}" || "${SHOW_RAW}" == "true" ]]; then
  __printf_color() { printf '%s\n' "$1"; }
else
  __printf_color() { [[ -t 1 ]] && printf '\e[38;5;%sm%s\e[0m\n' "${2:-$DEFAULT_COLOR}" "$1" || printf '%s\n' "$1"; }
fi
# - - - - - - - - - - - - - - - - - - - - - - - - -
# check for command
__cmd_exists() { (( $+commands[$1] )); }
__function_exists() { (( $+functions[$1] )); }
# - - - - - - - - - - - - - - - - - - - - - - - - -
# custom functions

# - - - - - - - - - - - - - - - - - - - - - - - - -
# Define Variables
DEFAULT_COLOR="254"
GEN_SCRIPT_REPLACE_ENV_EXIT_STATUS=0

# - - - - - - - - - - - - - - - - - - - - - - - - -
# Main application
__printf_color "User ID: $SET_UID"
__printf_color "User Name: $RUN_USER" 3
__printf_color "Script Name: $APPNAME" 4
__printf_color "Version: $VERSION" 5
__printf_color "Current Working directory: $GEN_SCRIPT_REPLACE_ENV_CWD" 6
# - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
# - - - - - - - - - - - - - - - - - - - - - - - - -
exit $GEN_SCRIPT_REPLACE_ENV_EXIT_STATUS
# - - - - - - - - - - - - - - - - - - - - - - - - -
# ex: ts=2 sw=2 et filetype=zsh
