#!/usr/bin/env zsh
# - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  GEN_SCRIPT_REPLACE_VERSION
# @@Author           :  GEN_SCRIPT_REPLACE_AUTHOR
# @@Contact          :  GEN_SCRIPT_REPLACE_EMAIL
# @@License          :  GEN_SCRIPT_REPLACE_LICENSE
# @@ReadME           :  GEN_SCRIPT_REPLACE_FILENAME --help
# @@Copyright        :  GEN_SCRIPT_REPLACE_COPYRIGHT
# @@Created          :  GEN_SCRIPT_REPLACE_DATE
# @@File             :  GEN_SCRIPT_REPLACE_FILENAME
# @@Description      :  GEN_SCRIPT_REPLACE_DESC
# @@Changelog        :  GEN_SCRIPT_REPLACE_CHANGELOG
# @@TODO             :  GEN_SCRIPT_REPLACE_TODO
# @@Other            :  GEN_SCRIPT_REPLACE_OTHER
# @@Resource         :  GEN_SCRIPT_REPLACE_RES
# @@Terminal App     :  GEN_SCRIPT_REPLACE_TERMINAL
# @@sudo/root        :  GEN_SCRIPT_REPLACE_SUDO
# @@Template         :  shell/zsh
# - - - - - - - - - - - - - - - - - - - - - - - - -
# shellcheck disable=all
# - - - - - - - - - - - - - - - - - - - - - - - - -
# script variables
APPNAME="${0:t}"
VERSION="GEN_SCRIPT_REPLACE_VERSION"
RUN_USER="${USER}"
SET_UID="${UID}"
SCRIPT_SRC_DIR="${0:A:h}"
GEN_SCRIPT_REPLACE_ENV_CWD="${PWD}"
GEN_SCRIPT_REPLACE_ENV_EXIT_STATUS=0
# - - - - - - - - - - - - - - - - - - - - - - - - -
# Define color variables
PRINTF_SET_BLACK='\e[1;30m'
PRINTF_SET_RED='\e[0;31m'
PRINTF_SET_GREEN='\e[0;32m'
PRINTF_SET_YELLOW='\e[1;33m'
PRINTF_SET_BLUE='\e[1;34m'
PRINTF_SET_PURPLE='\e[0;35m'
PRINTF_SET_CYAN='\e[0;36m'
PRINTF_SET_WHITE='\e[1;37m'
PRINTF_SET_RESET='\e[0m'
# - - - - - - - - - - - - - - - - - - - - - - - - -
# Define custom variables

# - - - - - - - - - - - - - - - - - - - - - - - - -
# script functions
# __printf_color "text" "$PRINTF_SET_COLOR"
if [[ -n "${NO_COLOR+x}" || "${SHOW_RAW}" == "true" ]]; then
  __printf_color() { printf '%s\n' "$1"; }
else
  __printf_color() { [[ -t 1 ]] && printf '%b%s%b\n' "${2:-$PRINTF_SET_RESET}" "$1" "$PRINTF_SET_RESET" || printf '%s\n' "$1"; }
fi
# - - - - - - - - - - - - - - - - - - - - - - - - -
# check for command
__cmd_exists() { (($+commands[$1])); }
__function_exists() { (($+functions[$1])); }
# - - - - - - - - - - - - - - - - - - - - - - - - -
# create custom functions

# - - - - - - - - - - - - - - - - - - - - - - - - -
trap '' EXIT
# - - - - - - - - - - - - - - - - - - - - - - - - -
# Main application
__printf_color "User ID: $SET_UID"
__printf_color "User Name: $RUN_USER" "$PRINTF_SET_YELLOW"
__printf_color "Script Name: $APPNAME" "$PRINTF_SET_BLUE"
__printf_color "Version: $VERSION" "$PRINTF_SET_PURPLE"
__printf_color "Current Working directory: $GEN_SCRIPT_REPLACE_ENV_CWD" "$PRINTF_SET_CYAN"
# - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
# - - - - - - - - - - - - - - - - - - - - - - - - -
exit $GEN_SCRIPT_REPLACE_ENV_EXIT_STATUS
# - - - - - - - - - - - - - - - - - - - - - - - - -
# ex: ts=2 sw=2 et filetype=zsh
